[programs.localnet]
tokadapt = "CWZ8fFJLqLPGgxKF7zzJcs4hVnUfZAPbVdMGaGtMHfaa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aankor/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -t 1000000 tests/*.ts"
